<template>
  <BaseCard class="br-4 column q-py-sm q-px-lg">
    <BaseCard class="q-pa-md q-my-lg br-4 bt-p" :class="{ 'bg-grey-12': !$q.dark.isActive }">
      <div class="flex items-center justify-between">
        <div class="text-subtitle1 column">
          {{ emailInfo }}
        </div>
        <div class="text-right">
          <q-fab color="primary" direction="left" icon="download" label="Download" padding="sm" push square>
            <q-fab-action color="primary" icon="fas fa-file-pdf" push @click="downloadPDFReport()">
              <q-tooltip anchor="top middle" self="bottom middle">Download PDF</q-tooltip>
            </q-fab-action>
            <q-fab-action color="primary  " icon="fas fa-file-csv" push @click="downloadCSVReport()">
              <q-tooltip anchor="top middle" self="bottom middle">Download CSV</q-tooltip>
            </q-fab-action>
          </q-fab>
        </div>
      </div>
    </BaseCard>

    <div class="hidden">
      <section ref="thepdf">
        <div class="q-my-xl q-py-xl html2pdf__page-break">
          <hr />
          <h3 class="ase-roboto text-center text-weight-medium">User Info</h3>
          <hr />
          <h4 class="text-center" style="margin-top: 200px">{{ username }}</h4>
          <h6 class="text-center" style="margin-top: 300px">
            Report generated by {{ fetchUserInfo.firstName }} on
            <br />
            <span>{{ readableDateNow }}</span>
          </h6>
        </div>
        <BaseTable
          bordered
          :columns="[
            { name: 'name', label: 'Description', field: 'name', align: 'left' },
            { name: 'count', label: 'Count', field: 'count', align: 'left' }
          ]"
          :rows="[
            { name: 'Completed mins', count: companyUsersStore.userAnalyticInfo.courseMinutes || 0 },
            { name: 'Enrolled Courses', count: companyUsersStore.userAnalyticInfo.activeCourses || 0 },
            { name: 'Badges Earned', count: companyUsersStore.userAnalyticInfo.badges || 0 },
            { name: 'Completed Labs', count: companyUsersStore.userAnalyticInfo.completedLabs || 0 },
            { name: 'Completed Challenges', count: companyUsersStore.userAnalyticInfo?.completedChallenges || 0 }
          ]"
          hide-bottom
          row-key="name"
          :table-header-style="{ backgroundColor: 'gray', color: 'white', fontWeight: 'bold' }"
          title="User Stats"
        >
          <template v-slot:body-cell-name="props">
            <q-td :props="props" style="background-color: lightgray">
              {{ props.value }}
            </q-td>
          </template>
        </BaseTable>
        <br />
        <BaseTable
          bordered
          :columns="columns"
          :rows="companyUsersStore.fetchIndividualUsersInfo.data"
          dense
          hide-bottom
          row-key="Course Name"
          :rows-per-page-options="[0]"
          :table-header-style="{ backgroundColor: 'gray', color: 'white', fontWeight: 'bold' }"
        >
          <template v-slot:body-cell-Course-Name="props">
            <q-td :props="props" style="background-color: lightgray">
              {{ props.value }}
            </q-td>
          </template>
        </BaseTable>
      </section>
    </div>
    <div class="row q-col-gutter-lg">
      <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
        <CompanyIndividualUserContent />
      </div>
      <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <div class="text-subtitle1">Statistics</div>
        <StatisticCard :stats="statistics" class="q-my-lg" />
        <div class="text-subtitle1">Recent Activities {{ companyUsersStore.recentActivitiesData.length }}</div>
        <div>
          <div class="row" v-if="!companyUsersStore.isLoading && companyUsersStore.recentActivitiesData.length > 0">
            <div class="q-pa-xs col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <BaseCard>
                <UserRecentActivites :recentActivities="companyUsersStore.recentActivitiesData" />
              </BaseCard>
            </div>
          </div>
          <div v-if="!companyUsersStore.isLoading && companyUsersStore.recentActivitiesData.length === 0">
            <span class="center">
              <div class="text-subtitle1 text-center">No recent activities</div>
            </span>
          </div>
        </div>
      </div>
    </div>
  </BaseCard>
</template>

<script>
import CompanyIndividualUserContent from 'components/company/CompanyIndividualUserContent.vue'
import html2pdf from 'html2pdf.js'
import { QSpinnerFacebook, LocalStorage, useQuasar } from 'quasar'
import { downloadCSV, readableDateNow, urlSafeBase64Decode } from 'src/utils/reuseFunctions'
import { useLoginStore } from 'src/store/pinia/login'
import { computed, ref, watch } from 'vue'
import useBreadcrumbs from 'src/composables/use-breadcrumb'

import { useRouter, useRoute } from 'vue-router'
import { onMounted } from 'vue'
import StatisticCard from 'src/components/common/StatisticCard.vue'
import UserRecentActivites from './UserRecentActivites.vue'
import { useLabStore } from 'src/store/pinia/lab'
import { storeToRefs } from 'pinia'
import { useCompanyConsumerStore } from 'src/store/pinia/companyUsers'
export default {
  name: 'CompanyIndividualUserInfo',
  components: { CompanyIndividualUserContent, StatisticCard, UserRecentActivites },
  setup() {
    const $q = useQuasar()
    const loginStore = useLoginStore()
    const fetchUserInfo = computed(() => loginStore.fetchUserInfo)

    const route = useRoute()
    const router = useRouter()
    const labStore = useLabStore()
    const companyUsersStore = useCompanyConsumerStore()

    const { isLoading: isLoadingLabs } = storeToRefs(labStore)

    const thepdf = ref(null)

    function routerUrlPath(path) {
      router.push(path)
    }

    async function downloadPDFReport() {
      const payload = {}
      payload.requester = LocalStorage.getItem('is_admin') ? 'admin' : 'self'
      payload.email = urlSafeBase64Decode(route.params.email)

      companyUsersStore.downloadXLSReportActionIndividual(payload)

      html2pdf(thepdf.value, { filename: undefined })
    }

    const columns = [
      { name: 'Course Name', label: 'Course Name', field: 'Course Name', align: 'left' },
      { name: 'Total course Minutes', label: 'Total Course Minutes', field: 'Total course Minutes', align: 'left' },
      { name: 'Total completed Minutes', label: 'Total Completed Minutes', field: 'Total completed Minutes', align: 'left' },
      { name: 'Total Video Minutes', label: 'Total Video Minutes', field: 'Total Video Minutes', align: 'left' },
      { name: 'Total Lab Minutes', label: 'Total Lab Minutes', field: 'Total Lab Minutes', align: 'left' },
      { name: 'Percentage', label: 'Percentage', field: 'Percentage', align: 'left' }
    ]

    async function downloadCSVReport() {
      const payload = {}
      payload.requester = LocalStorage.getItem('is_admin') ? 'admin' : 'self'
      payload.email = urlSafeBase64Decode(route.params.email)
      await companyUsersStore.downloadXLSReportActionIndividual(payload)

      const status = downloadCSV(columns, companyUsersStore.fetchIndividualUsersInfo?.data ?? [], `Reports - ${readableDateNow()}`)

      if (!status) {
        $q.notify({
          message: 'Error while exporting',
          color: 'negative',
          position: 'top',
          timeout: 2000
        })
      }
    }

    onMounted(() => {
      const data = { email: urlSafeBase64Decode(route.params.email) }

      labStore.fetchIndividualUserChallengeSolvedCount({ email: urlSafeBase64Decode(route.params.email) })
      companyUsersStore.fetchUserDashboardAnalytic({ user_id: urlSafeBase64Decode(route.params.email) })
      companyUsersStore.fetchUserActiveCourses(data)
      companyUsersStore.fetchUserCompletedCourses(data)
      companyUsersStore.recentActivities({ user_id: urlSafeBase64Decode(route.params.email) })

      useBreadcrumbs().setBreadcrumb([
        {
          label: urlSafeBase64Decode(route.params.email)
        }
      ])
    })

    watch(
      () => companyUsersStore.isLoading,
      (value) => {
        if (value) {
          $q.loading.show({
            spinner: QSpinnerFacebook,
            spinnerColor: 'white',
            spinnerSize: 140,
            message: 'Hang on...',
            messageColor: 'white'
          })
        } else {
          $q.loading.hide()
        }
      }
    )

    watch(isLoadingLabs, (value) => {
      if (value) {
        $q.loading.show({
          spinner: QSpinnerFacebook,
          spinnerColor: 'white',
          spinnerSize: 140,
          message: 'Hang on...',
          messageColor: 'white'
        })
      } else {
        $q.loading.hide()
      }
    })

    const statistics = computed(() => {
      return [
        {
          title: 'Enrolled courses',
          count: companyUsersStore.userAnalyticInfo?.activeCourses || 0
        },
        {
          title: 'Badges',
          count: companyUsersStore.userAnalyticInfo?.badges || 0
        },
        {
          title: 'Completed Labs',
          count: companyUsersStore.userAnalyticInfo?.completedLabs || 0
        },
        {
          title: 'Completed Challenges',
          count: companyUsersStore.userAnalyticInfo?.completedChallenges || 0
        }
      ]
    })

    return {
      loginStore,
      fetchUserInfo,
      ...useBreadcrumbs(),
      routerUrlPath,
      emailInfo: urlSafeBase64Decode(route.params.email),
      username: urlSafeBase64Decode(route.params.username),
      readableDateNow: readableDateNow(),
      downloadPDFReport,
      thepdf,
      columns,
      downloadCSVReport,
      statistics,
      labStore,
      companyUsersStore
    }
  }
}
</script>

<style scoped>
.bordered_style {
  padding: 12px;
  border: 1px solid #f2f2f2;
  border-radius: 0px;
}
</style>
