<template>
  <div>
    <BaseTable
      :columns="columns"
      row-key="email"
      :rows="companyAdmin.adminUsers"
      :rows-per-page-options="[0]"
      virtual-scroll
      style="max-height: calc(100vh - 300px)"
      hide-pagination
      :loading="companyAdmin.loading"
      @virtual-scroll="loadMore"
    >
      <template v-slot:body-cell="props">
        <q-td :props="props" @click="getUserInfo(props.row)">
          {{ props.value }}
        </q-td>
      </template>
      <template v-slot:top-right>
        <div class="text-right">
          <q-fab color="primary" direction="left" icon="download" label="Download" padding="sm" push square>
            <q-fab-action color="primary" icon="fas fa-file-pdf" push @click="downloadPDFReport()">
              <q-tooltip anchor="top middle" self="bottom middle">Download PDF</q-tooltip>
            </q-fab-action>
            <q-fab-action color="primary" icon="fas fa-file-csv" push @click="downloadCSVReport()">
              <q-tooltip anchor="top middle" self="bottom middle">Download CSV</q-tooltip>
            </q-fab-action>
          </q-fab>
        </div>
      </template>
      <template #body-cell-index="props">
        <q-td>
          {{ props.pageIndex + 1 }}
        </q-td>
      </template>
    </BaseTable>

    <div class="hidden">
      <section class="q-my-xl q-py-xl html2pdf__page-break" ref="thepdf">
        <hr />
        <h3 class="ase-roboto text-center text-weight-medium">Administrators List</h3>
        <hr />
        <h6 class="text-center" style="margin-top: 500px">
          Report generated by {{ fetchUserInfo.firstName }} on
          <br />
          <span>{{ readableDateNow() }}</span>
        </h6>
        <div class="q-pa-md" style="border: 2px solid gray">
          <BaseTable :columns="columns" :rows="companyAdmin.adminUsers" hide-bottom row-key="index" :rows-per-page-options="[0]">
            <template #body-cell-index="props">
              <q-td>
                {{ props.pageIndex + 1 }}
              </q-td>
            </template>
          </BaseTable>
        </div>
      </section>
    </div>
  </div>
</template>

<script>
import html2pdf from 'html2pdf.js'
import { downloadCSV, readableDateNow, urlSafeBase64Encode } from 'src/utils/reuseFunctions'

import { useLoginStore } from 'src/store/pinia/login'
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useQuasar } from 'quasar'
import { useCompanyAdmin } from 'src/store/pinia/company/admin'
export default {
  name: 'CompanyAdminOpsTable',

  setup() {
    const pagination = { sortBy: 'desc', descending: false, page: 1, rowsPerPage: 8 }
    const columns = [
      { name: 'index', label: 'Number', field: 'index', sortable: true, align: 'left' },
      { name: 'fullName', label: 'Full Name', field: 'full_name', sortable: true, align: 'left' },
      { name: 'email', label: 'Email', field: 'email', sortable: true, align: 'left' }
    ]
    const router = useRouter()
    const $q = useQuasar()
    const thepdf = ref(null)
    const loginStore = useLoginStore()
    const fetchUserInfo = computed(() => {
      return loginStore.fetchUserInfo
    })

    const filename = computed(() => {
      return `Administrators List - ${readableDateNow()}`
    })

    function downloadPDFReport() {
      html2pdf(thepdf.value, { filename: filename.value })
    }

    function downloadCSVReport() {
      const status = downloadCSV(this.columns, this.getAdminUsers, this.filename)

      if (!status) {
        $q.notify({
          message: 'Error while exporting',
          color: 'negative',
          position: 'top',
          timeout: 2000
        })
      }
    }

    function getUserInfo(row) {
      router.push(`/portal/company/profile-info/${urlSafeBase64Encode(row.email)}/${urlSafeBase64Encode(row.fullName)}`)
    }

    const companyAdmin = useCompanyAdmin()

    async function fetchCompanyAdmin() {
      await companyAdmin.fetchAdminUsers()
    }

    async function loadMore(details) {
      if (details.index === companyAdmin.adminUsers.length - 1 && companyAdmin.payload.LastEvaluatedKey && !companyAdmin.loading) {
        fetchCompanyAdmin()
      }
    }

    function bootingAdmin() {
      if (companyAdmin.adminUsers?.length) return
      fetchCompanyAdmin()
    }
    bootingAdmin()
    return {
      loginStore,
      fetchUserInfo,
      columns,
      filename,
      readableDateNow,
      thepdf,
      downloadPDFReport,
      downloadCSVReport,
      getUserInfo,
      loadMore,
      companyAdmin
    }
  }
}
</script>

<style lang="sass">
.q-table th
  font-size: 14px
  font-weight: bolder

.q-table td
  cursor: pointer
</style>
